'use client';
import {useEffect,useState} from 'react';import {Layout} from '../../components/Layout';import {api,label,request,useWorkspace} from '../../components/useWorkspace';
export default function Reports(){
 const me=useWorkspace(),[rows,setRows]=useState<any[]>([]),[name,setName]=useState('Monthly performance report'),[type,setType]=useState('MONTHLY_ORGANIZATION'),[error,setError]=useState('');
 const load=()=>{fetch(api+'/reports',{credentials:'include'}).then(r=>r.json()).then(x=>{if(x.success)setRows(x.data)})};
 useEffect(()=>{load()},[]);
 async function create(e:any){e.preventDefault();try{await request('/reports',{method:'POST',body:JSON.stringify({name,type,filters:{}})});load()}catch(e:any){setError(e.message)}}
 async function download(id:string,format:string){const r=await fetch(`${api}/reports/${id}/export`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({format})});if(!r.ok){setError('Export failed.');return}const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`report.${format}`;a.click();URL.revokeObjectURL(a.href)}
 if(!me)return <div className="loading">Loading reports…</div>;
 return <Layout me={me}><header className="page-head"><div><p className="eyebrow">REPORTING</p><h1>Reports</h1><p>Save report configurations and regenerate them from current data.</p></div></header><section className="card report-builder"><h2>Create a report</h2><form onSubmit={create}><div><label>Report name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Report type<select value={type} onChange={e=>setType(e.target.value)}>{['CAMPAIGN','CLIENT','TEAM','TASK','MONTHLY_ORGANIZATION'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label></div>{error&&<p className="form-error">{error}</p>}<button>Create report</button></form></section><section className="card table-card"><div className="card-title"><h2>Saved reports</h2></div>{rows.length?<table><thead><tr><th>Report</th><th>Type</th><th>Created by</th><th>Export</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.name}<small>{new Date(x.createdAt).toLocaleDateString()}</small></td><td>{label(x.type)}</td><td>{x.creator.name}</td><td><div className="button-row"><button onClick={()=>download(x.id,'csv')}>CSV</button><button className="secondary" onClick={()=>download(x.id,'pdf')}>PDF</button></div></td></tr>)}</tbody></table>:<p className="empty">No saved reports yet.</p>}</section></Layout>
}
