'use client';import Link from 'next/link';import {useCallback,useEffect,useState} from 'react';import {api,label} from './useWorkspace';import {useRealtime} from './useRealtime';
export const ranges=[['Last 7 days',7],['Last 30 days',30],['Last 90 days',90],['This year',365]] as const;
export function rangeQuery(days:number){const end=new Date(),start=new Date(Date.now()-(days-1)*86400000);return `startDate=${start.toISOString().slice(0,10)}&endDate=${end.toISOString().slice(0,10)}`}
export function AnalyticsNav(){return <nav className="analytics-nav">{[['Overview','/analytics'],['Campaigns','/analytics/campaigns'],['Tasks','/analytics/tasks'],['Team','/analytics/team'],['Clients','/analytics/clients']].map(x=><Link key={x[1]} href={x[1]}>{x[0]}</Link>)}</nav>}
export function DateRange({days,setDays}:{days:number,setDays:(x:number)=>void}){return <select aria-label="Date range" value={days} onChange={e=>setDays(+e.target.value)}>{ranges.map(x=><option key={x[1]} value={x[1]}>{x[0]}</option>)}</select>}
export function Metrics({items}:{items:[string,any][]}){return <section className="analytics-metrics">{items.map(([k,v])=><article className="metric" key={k}><small>{k}</small><strong>{typeof v==='number'?v.toLocaleString():v}</strong></article>)}</section>}
export function Bars({data}:{data:{date:string,count:number}[]}){const max=Math.max(1,...data.map(x=>x.count));return <section className="card chart"><div className="card-title"><h2>Task completion trend</h2></div>{data.length?<div className="bars">{data.map(x=><div key={x.date}><span style={{height:`${Math.max(6,x.count/max*150)}px`}} title={`${x.count} completed`}/><small>{x.date.slice(5)}</small></div>)}</div>:<p className="empty">No completed tasks in this period.</p>}</section>}
export function useAnalytics(path:string,days:number){const [state,setState]=useState<any>({loading:true}),[revision,setRevision]=useState(0);const refresh=useCallback(()=>setRevision(x=>x+1),[]);useRealtime(refresh);useEffect(()=>{setState({loading:true});fetch(`${api}${path}${path.includes('?')?'&':'?'}${rangeQuery(days)}`,{credentials:'include'}).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error?.message||'Unable to load analytics');setState({data:x.data,pagination:x.pagination})}).catch(error=>setState({error:error.message}))},[path,days,revision]);return state}
export function AnalyticsState({state}:{state:any}){if(state.loading)return <div className="skeleton-grid">{[1,2,3,4].map(x=><i key={x}/>)}</div>;if(state.error)return <section className="card error-state"><h2>Unable to load analytics</h2><p>{state.error}</p></section>;return null}
export function statusPill(s:string){return <span className="pill green">{label(s)}</span>}
