"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api, label } from "./useWorkspace";
import { formatDuration } from "./TaskTimer";
import { useRealtime } from "./useRealtime";
const columns = ["TODO", "ASSIGNED", "IN_PROGRESS", "COMPLETED"];
export function TaskBoard({ me }: { me: any }) {
  const [tasks, setTasks] = useState<any[]>([]), [options, setOptions] = useState<any>({ teams: [], campaigns: [] }), [filters, setFilters] = useState<any>({ search: "", team_id: "", campaign_id: "", priority: "", due: "" }), [error, setError] = useState("");
  const load = useCallback(async () => { try { const params = new URLSearchParams({ page_size: "100", ...Object.fromEntries(Object.entries(filters).filter(([, v]) => v)) } as any), [a, b] = await Promise.all([fetch(`${api}/tasks?${params}`, { credentials: "include" }), fetch(`${api}/task-board/options`, { credentials: "include" })]), [x, y] = await Promise.all([a.json(), b.json()]); if (!a.ok) throw Error(x.error?.message); setTasks(x.data); if (y.success) setOptions(y.data); setError(""); } catch (e: any) { setError(e.message); } }, [filters]);
  useEffect(() => { const t = setTimeout(load, 150); return () => clearTimeout(t); }, [load]); useRealtime(load);
  const grouped = useMemo(() => Object.fromEntries(columns.map(c => [c, tasks.filter(t => t.status === c)])), [tasks]), set = (k: string, v: string) => setFilters((x: any) => ({ ...x, [k]: v }));
  return <><header className="page-head"><div><p className="eyebrow">OPERATIONS</p><h1>{me.role === "EMPLOYEE" ? "My Tasks" : me.role === "CEO" ? "Task Overview" : `${label(me.role)} Task Board`}</h1><p>Live, authoritative task execution across your authorized scope.</p></div>{me.role === "TEAM_LEAD" && <Link className="button" href="/tasks/new">+ Create task</Link>}</header><div className="board-filters"><input placeholder="Search tasks, campaigns, or employees…" value={filters.search} onChange={e => set("search", e.target.value)} />{me.role !== "EMPLOYEE" && <select value={filters.team_id} onChange={e => set("team_id", e.target.value)}><option value="">All teams</option>{options.teams.map((x: any) => <option key={x.id} value={x.id}>{x.name}</option>)}</select>}<select value={filters.campaign_id} onChange={e => set("campaign_id", e.target.value)}><option value="">All campaigns</option>{options.campaigns.map((x: any) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={filters.priority} onChange={e => set("priority", e.target.value)}><option value="">All priorities</option>{["LOW", "MEDIUM", "HIGH", "URGENT"].map(x => <option key={x}>{x}</option>)}</select><select value={filters.due} onChange={e => set("due", e.target.value)}><option value="">Any deadline</option><option value="today">Due today</option><option value="overdue">Overdue</option><option value="upcoming">Upcoming</option></select></div>{error && <section className="card error-state">{error}</section>}<div className="task-board">{columns.map(column => <section className="board-column" key={column}><header><span>{label(column)}</span><b>{grouped[column].length}</b></header><div>{grouped[column].map((task: any) => { const active = task.workSessions?.[0], overdue = task.dueDate && new Date(task.dueDate) < new Date() && !["COMPLETED", "CANCELLED"].includes(task.status); return <Link href={`/tasks/${task.id}`} className={`task-card ${overdue ? "task-overdue" : ""}`} key={task.id}><h3>{task.title}</h3><p>{task.campaign.name}</p><div className="task-owner"><span>{task.assignees[0]?.user.name?.[0] || "–"}</span>{task.assignees[0]?.user.name || "Unassigned"}</div><div className="task-time-row"><span>Est. {task.estimatedDurationSeconds ? formatDuration(task.estimatedDurationSeconds) : "—"}</span><span>Actual {formatDuration(task.actualDurationSeconds)}</span></div>{active && <p className="tracking-badge">● Tracking since {new Date(active.startedAt).toLocaleTimeString()}</p>}{overdue && <p className="overdue">⚠ Overdue</p>}<footer><span className={`pill priority-${task.priority.toLowerCase()}`}>{label(task.priority)}</span><time>{task.dueDate ? new Date(task.dueDate).toLocaleString() : "No due date"}</time></footer></Link>; })}</div></section>)}</div></>;
}
