import type {LucideIcon} from 'lucide-react';
import {Activity,BarChart3,Bell,BriefcaseBusiness,Building2,CalendarDays,ClipboardCheck,Cog,FileCheck2,Files,LayoutDashboard,ListTodo,UsersRound,Workflow} from 'lucide-react';
export type WorkspaceRole='CEO'|'MANAGER'|'TEAM_LEAD'|'EMPLOYEE';
type NavItem={label:string;href:string;icon:LucideIcon;permission?:string};
type NavGroup={label:string;items:NavItem[]};
const common={dashboard:{label:'Dashboard',href:'/dashboard',icon:LayoutDashboard},calendar:{label:'Calendar',href:'/calendar',icon:CalendarDays,permission:'tasks.view'},notifications:{label:'Notifications',href:'/notifications',icon:Bell}};
export const workspacePolicies:Record<WorkspaceRole,{scope:string;label:string;navigation:NavGroup[]}>= {
 CEO:{scope:'organization',label:'Organization workspace',navigation:[{label:'Main',items:[common.dashboard,{label:'Clients',href:'/clients',icon:Building2,permission:'clients.view'},{label:'Campaigns',href:'/campaigns',icon:BriefcaseBusiness,permission:'campaigns.view'},{label:'SOP Operations',href:'/sops',icon:Workflow,permission:'sop.view'},{label:'Tasks',href:'/tasks',icon:ListTodo,permission:'tasks.view'},common.calendar,{label:'Analytics',href:'/analytics',icon:BarChart3}]},{label:'Organization',items:[{label:'Teams',href:'/teams',icon:UsersRound,permission:'teams.view'},{label:'Members',href:'/members',icon:UsersRound,permission:'members.view'},{label:'Workload',href:'/analytics/team',icon:Activity}]},{label:'Reporting',items:[{label:'Reports',href:'/reports',icon:Files},{label:'Approvals',href:'/tasks?status=IN_REVIEW',icon:ClipboardCheck},{label:'Activity',href:'/notifications',icon:Activity}]},{label:'System',items:[common.notifications,{label:'Settings',href:'/settings',icon:Cog,permission:'organization.update'}]}]},
 MANAGER:{scope:'operations',label:'Operations workspace',navigation:[{label:'Main',items:[common.dashboard,{label:'Clients',href:'/clients',icon:Building2,permission:'clients.view'},{label:'Campaigns',href:'/campaigns',icon:BriefcaseBusiness,permission:'campaigns.view'},{label:'SOP Operations',href:'/sops',icon:Workflow,permission:'sop.view'},{label:'Tasks',href:'/tasks',icon:ListTodo,permission:'tasks.view'},common.calendar,{label:'Analytics',href:'/analytics',icon:BarChart3}]},{label:'Team management',items:[{label:'Teams',href:'/teams',icon:UsersRound,permission:'teams.view'},{label:'Workload',href:'/analytics/team',icon:Activity}]},{label:'Reporting',items:[{label:'Reports',href:'/reports',icon:Files},{label:'Approvals',href:'/tasks?status=IN_REVIEW',icon:ClipboardCheck},{label:'Activity',href:'/notifications',icon:Activity}]},{label:'System',items:[common.notifications]}]},
 TEAM_LEAD:{scope:'team',label:'Team workspace',navigation:[{label:'Main',items:[common.dashboard,{label:'Campaigns',href:'/campaigns',icon:BriefcaseBusiness,permission:'campaigns.view'},{label:'SOP Operations',href:'/sops',icon:Workflow,permission:'sop.view'},{label:'Tasks',href:'/tasks',icon:ListTodo,permission:'tasks.view'},common.calendar]},{label:'Team',items:[{label:'My Team',href:'/teams',icon:UsersRound,permission:'teams.view'},{label:'Team Workload',href:'/analytics/team',icon:Activity}]},{label:'Performance',items:[{label:'Analytics',href:'/analytics',icon:BarChart3},{label:'Reports',href:'/reports',icon:Files}]},{label:'System',items:[common.notifications]}]},
 EMPLOYEE:{scope:'own',label:'Personal workspace',navigation:[{label:'Main',items:[common.dashboard,{label:'My Tasks',href:'/my-tasks',icon:ListTodo,permission:'tasks.view'},common.calendar]},{label:'My work',items:[{label:'My Campaigns',href:'/campaigns',icon:BriefcaseBusiness,permission:'campaigns.view'},{label:'My SOPs',href:'/sops',icon:Workflow,permission:'sop.view'},{label:'My Deliverables',href:'/my-tasks',icon:FileCheck2,permission:'tasks.view'}]},{label:'Performance',items:[{label:'My Performance',href:'/analytics',icon:BarChart3}]},{label:'System',items:[common.notifications]}]},
};
export function hasPermission(me:any,permission?:string){if(!permission)return true;const grants:string[]=me?.permissions||[];return grants.includes('*')||grants.includes(permission)}
export function navigationFor(me:any){const policy=workspacePolicies[me.role as WorkspaceRole]||workspacePolicies.EMPLOYEE;return policy.navigation.map(g=>({...g,items:g.items.filter(i=>hasPermission(me,i.permission))})).filter(g=>g.items.length)}
export function canAccessPath(me:any,path:string){const rules:Record<string,WorkspaceRole[]>={'/tasks/new':['CEO','MANAGER','TEAM_LEAD'],'/analytics/team':['CEO','MANAGER','TEAM_LEAD'],'/settings':['CEO'],'/members':['CEO','MANAGER'],'/invitations':['CEO','MANAGER'],'/clients':['CEO','MANAGER'],'/teams':['CEO','MANAGER','TEAM_LEAD'],'/reports':['CEO','MANAGER','TEAM_LEAD'],'/tasks':['CEO','MANAGER','TEAM_LEAD'],'/my-tasks':['EMPLOYEE']};const match=Object.keys(rules).sort((a,b)=>b.length-a.length).find(route=>path===route||path.startsWith(route+'/'));return !match||rules[match].includes(me.role)}
