import Fastify from 'fastify'; import cors from '@fastify/cors'; import cookie from '@fastify/cookie'; import jwt from '@fastify/jwt'; import bcrypt from 'bcryptjs'; import crypto from 'node:crypto'; import {PrismaClient, Role, MemberStatus, InvitationStatus} from '@prisma/client'; import {z} from 'zod';
const db=new PrismaClient(); const app=Fastify({logger:true}); const permissions:Record<Role,string[]>={OWNER:['*'],MANAGER:['organization.view','users.view','users.invite','teams.view','teams.create','teams.update','teams.members.manage'],TEAM_LEAD:['organization.view','users.view','teams.view','teams.members.view'],EMPLOYEE:['profile.view','profile.update','organization.view','teams.view'],CLIENT:['profile.view','profile.update']};
await app.register(cors,{origin:'http://localhost:3000',credentials:true}); await app.register(cookie); await app.register(jwt,{secret:process.env.JWT_SECRET||'development-only-change-me',cookie:{cookieName:'dm_session',signed:false}});
const ok=(data:any)=>({success:true,data}); const fail=(code:string,message:string)=>({success:false,error:{code,message}}); const token=(id:string)=>crypto.createHash('sha256').update(id).digest('hex');
app.setErrorHandler((e:any,_q,r)=>r.status(e.statusCode||500).send(fail(e.code==='P2002'?'CONFLICT':'SERVER_ERROR',e.message==='Unauthorized'?'Authentication required':'Something went wrong.')));
async function context(req:any,reply:any){try{const p=await req.jwtVerify<{userId:string,organizationId:string}>(); const membership=await db.membership.findUnique({where:{userId_organizationId:{userId:p.userId,organizationId:p.organizationId}},include:{user:true,organization:true}}); if(!membership||membership.status!==MemberStatus.ACTIVE)throw Error(); return membership;}catch{reply.status(401).send(fail('UNAUTHORIZED','Authentication required.')); return null;}}
function allowed(m:any,p:string){return permissions[m.role].includes('*')||permissions[m.role].includes(p)} function guard(p:string){return async(q:any,r:any)=>{const m=await context(q,r); if(!m)return; if(!allowed(m,p)){r.status(403).send(fail('FORBIDDEN','You do not have permission to perform this action.'));return;} q.member=m;};}
async function activity(org:string,actor:string,action:string,entityType:string,entityId?:string){await db.activityLog.create({data:{organizationId:org,actorUserId:actor,action,entityType,entityId}})}
app.post('/api/v1/auth/register',async(q,r)=>{const v=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8),organizationName:z.string().min(2)}).parse(q.body); const slug=v.organizationName.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+crypto.randomBytes(2).toString('hex'); const user=await db.user.create({data:{name:v.name,email:v.email.toLowerCase(),passwordHash:await bcrypt.hash(v.password,12)}}); const org=await db.organization.create({data:{name:v.organizationName,slug}}); await db.membership.create({data:{userId:user.id,organizationId:org.id,role:Role.OWNER}}); const session=app.jwt.sign({userId:user.id,organizationId:org.id}); r.setCookie('dm_session',session,{httpOnly:true,sameSite:'lax',path:'/'}); return ok({user:{id:user.id,name:user.name,email:user.email},organization:org});});
app.post('/api/v1/auth/login',async(q,r)=>{const v=z.object({email:z.string().email(),password:z.string()}).parse(q.body); const user=await db.user.findUnique({where:{email:v.email.toLowerCase()},include:{memberships:{include:{organization:true}}}}); if(!user||!await bcrypt.compare(v.password,user.passwordHash))return r.status(401).send(fail('INVALID_CREDENTIALS','Invalid email or password.')); const m=user.memberships.find(x=>x.status===MemberStatus.ACTIVE); if(!m)return r.status(403).send(fail('ACCOUNT_INACTIVE','No active organization membership.')); r.setCookie('dm_session',app.jwt.sign({userId:user.id,organizationId:m.organizationId}),{httpOnly:true,sameSite:'lax',path:'/'});return ok({user:{id:user.id,name:user.name,email:user.email},organization:m.organization,role:m.role});});
app.post('/api/v1/auth/logout',async(_q,r)=>{r.clearCookie('dm_session',{path:'/'});return ok({});});
app.post('/api/v1/auth/forgot-password',async(q)=>{const v=z.object({email:z.string().email()}).parse(q.body);const user=await db.user.findUnique({where:{email:v.email.toLowerCase()}});if(!user)return ok({message:'If an account exists, reset instructions have been sent.'});const raw=crypto.randomBytes(32).toString('base64url');await db.passwordResetToken.create({data:{userId:user.id,tokenHash:token(raw),expiresAt:new Date(Date.now()+3600000)}});return ok({message:'If an account exists, reset instructions have been sent.',developmentResetToken:raw});});
app.post('/api/v1/auth/reset-password',async(q,r)=>{const v=z.object({token:z.string(),password:z.string().min(8)}).parse(q.body);const reset=await db.passwordResetToken.findUnique({where:{tokenHash:token(v.token)}});if(!reset||reset.usedAt||reset.expiresAt<new Date())return r.status(422).send(fail('INVALID_RESET_TOKEN','This reset link is invalid or expired.'));await db.$transaction([db.user.update({where:{id:reset.userId},data:{passwordHash:await bcrypt.hash(v.password,12)}}),db.passwordResetToken.update({where:{id:reset.id},data:{usedAt:new Date()}})]);return ok({message:'Password updated. You can now sign in.'});});
app.get('/api/v1/me',async(q,r)=>{const m=await context(q,r);if(!m)return;return ok({user:m.user,organization:m.organization,role:m.role,permissions:permissions[m.role]});});
app.get('/api/v1/dashboard', {preHandler:guard('organization.view')},async(q:any)=>{const org=q.member.organizationId;const [members,active,teams,invites,activities]=await Promise.all([db.membership.count({where:{organizationId:org}}),db.membership.count({where:{organizationId:org,status:MemberStatus.ACTIVE}}),db.team.count({where:{organizationId:org}}),db.invitation.count({where:{organizationId:org,status:InvitationStatus.PENDING}}),db.activityLog.findMany({where:{organizationId:org},take:8,orderBy:{createdAt:'desc'},include:{actor:true}})]);return ok({members,active,teams,invites,status:q.member.organization.status,activities});});
app.get('/api/v1/members',{preHandler:guard('users.view')},async(q:any)=>ok(await db.membership.findMany({where:{organizationId:q.member.organizationId},include:{user:true},orderBy:{joinedAt:'desc'}})));
app.patch('/api/v1/members/:id',{preHandler:guard('users.update')},async(q:any,r)=>{const v=z.object({role:z.nativeEnum(Role).optional(),status:z.nativeEnum(MemberStatus).optional()}).parse(q.body);const target=await db.membership.findFirst({where:{id:q.params.id,organizationId:q.member.organizationId}});if(!target)return r.status(404).send(fail('NOT_FOUND','Member not found.'));if(target.role===Role.OWNER&&q.member.role!==Role.OWNER)return r.status(403).send(fail('FORBIDDEN','Only an owner can change an owner.'));const updated=await db.membership.update({where:{id:target.id},data:v});await activity(q.member.organizationId,q.member.userId,'ROLE_CHANGED','membership',target.id);return ok(updated);});
app.get('/api/v1/teams',{preHandler:guard('teams.view')},async(q:any)=>ok(await db.team.findMany({where:{organizationId:q.member.organizationId},include:{teamLead:true,_count:{select:{members:true}}},orderBy:{createdAt:'desc'}})));
app.post('/api/v1/teams',{preHandler:guard('teams.create')},async(q:any)=>{const v=z.object({name:z.string().min(2),description:z.string().optional(),teamLeadId:z.string().optional()}).parse(q.body);if(v.teamLeadId&&!await db.membership.findFirst({where:{organizationId:q.member.organizationId,userId:v.teamLeadId,status:MemberStatus.ACTIVE}}))throw Object.assign(new Error('Team lead must be an active member.'),{statusCode:422});const team=await db.team.create({data:{...v,organizationId:q.member.organizationId}});await activity(q.member.organizationId,q.member.userId,'TEAM_CREATED','team',team.id);return ok(team);});
app.get('/api/v1/teams/:id',{preHandler:guard('teams.view')},async(q:any,r)=>{const team=await db.team.findFirst({where:{id:q.params.id,organizationId:q.member.organizationId},include:{teamLead:true,members:{include:{user:true}}}});return team?ok(team):r.status(404).send(fail('NOT_FOUND','Team not found.'));});
app.post('/api/v1/teams/:id/members',{preHandler:guard('teams.members.manage')},async(q:any,r)=>{const v=z.object({userId:z.string()}).parse(q.body);const team=await db.team.findFirst({where:{id:q.params.id,organizationId:q.member.organizationId}});const m=await db.membership.findFirst({where:{organizationId:q.member.organizationId,userId:v.userId,status:MemberStatus.ACTIVE}});if(!team||!m)return r.status(404).send(fail('NOT_FOUND','Team or member not found.'));return ok(await db.teamMember.upsert({where:{teamId_userId:{teamId:team.id,userId:v.userId}},create:{teamId:team.id,userId:v.userId},update:{}}));});
app.get('/api/v1/invitations',{preHandler:guard('users.invite')},async(q:any)=>ok(await db.invitation.findMany({where:{organizationId:q.member.organizationId},orderBy:{createdAt:'desc'}})));
app.post('/api/v1/invitations',{preHandler:guard('users.invite')},async(q:any)=>{const v=z.object({email:z.string().email(),role:z.nativeEnum(Role),teamId:z.string().optional()}).parse(q.body);const raw=crypto.randomBytes(32).toString('base64url');const invite=await db.invitation.create({data:{organizationId:q.member.organizationId,email:v.email.toLowerCase(),role:v.role,teamId:v.teamId,invitedById:q.member.userId,tokenHash:token(raw),expiresAt:new Date(Date.now()+7*86400000)}});await activity(q.member.organizationId,q.member.userId,'USER_INVITED','invitation',invite.id);return ok({...invite,invitationToken:raw});});
app.post('/api/v1/invitations/accept',async(q,r)=>{const v=z.object({token:z.string(),name:z.string().min(2),password:z.string().min(8)}).parse(q.body);const invite=await db.invitation.findUnique({where:{tokenHash:token(v.token)}});if(!invite||invite.status!==InvitationStatus.PENDING||invite.expiresAt<new Date())return r.status(422).send(fail('INVALID_INVITATION','This invitation is invalid or expired.'));let user=await db.user.findUnique({where:{email:invite.email}});if(!user)user=await db.user.create({data:{name:v.name,email:invite.email,passwordHash:await bcrypt.hash(v.password,12)}});await db.$transaction([db.membership.upsert({where:{userId_organizationId:{userId:user.id,organizationId:invite.organizationId}},create:{userId:user.id,organizationId:invite.organizationId,role:invite.role},update:{role:invite.role,status:MemberStatus.ACTIVE}}),db.invitation.update({where:{id:invite.id},data:{status:InvitationStatus.ACCEPTED}})]);if(invite.teamId)await db.teamMember.upsert({where:{teamId_userId:{teamId:invite.teamId,userId:user.id}},create:{teamId:invite.teamId,userId:user.id},update:{}});r.setCookie('dm_session',app.jwt.sign({userId:user.id,organizationId:invite.organizationId}),{httpOnly:true,sameSite:'lax',path:'/'});return ok({message:'Invitation accepted.'});});
app.patch('/api/v1/organization',{preHandler:guard('organization.update')},async(q:any)=>{const v=z.object({name:z.string().min(2).optional(),industry:z.string().optional(),timezone:z.string().optional(),currency:z.string().optional(),logoUrl:z.string().url().optional()}).parse(q.body);const org=await db.organization.update({where:{id:q.member.organizationId},data:v});await activity(org.id,q.member.userId,'ORGANIZATION_UPDATED','organization',org.id);return ok(org);});
app.patch('/api/v1/profile',async(q,r)=>{const m=await context(q,r);if(!m)return;const v=z.object({name:z.string().min(2).optional(),phone:z.string().optional(),jobTitle:z.string().optional(),bio:z.string().max(500).optional(),timezone:z.string().optional()}).parse(q.body);return ok(await db.user.update({where:{id:m.userId},data:v}));});
app.listen({port:Number(process.env.PORT||4000),host:'0.0.0.0'});
