import Fastify from 'fastify'; import cors from '@fastify/cors'; import cookie from '@fastify/cookie'; import jwt from '@fastify/jwt'; import bcrypt from 'bcryptjs'; import crypto from 'node:crypto'; import {PrismaClient, Role, MemberStatus, InvitationStatus} from '@prisma/client'; import {z} from 'zod';
import {registerTaskRoutes} from './taskRoutes.js';
import {registerPortalRoutes} from './portalRoutes.js';
import {registerAnalyticsRoutes} from './analyticsRoutes.js';
import {canAssignRole, hasPermission, rolePermissions} from './authorization.js';
const db=new PrismaClient(); const app=Fastify({logger:true});
const frontendUrl=process.env.FRONTEND_URL||'http://localhost:3000';
const isProduction=process.env.NODE_ENV==='production';
const sessionCookie={httpOnly:true,secure:isProduction,sameSite:isProduction?'none' as const:'lax' as const,path:'/'};
await app.register(cors,{origin:frontendUrl,credentials:true}); await app.register(cookie); await app.register(jwt,{secret:process.env.JWT_SECRET||'development-only-change-me',cookie:{cookieName:'dm_session',signed:false}});
const ok=(data:any)=>({success:true,data}); const fail=(code:string,message:string)=>({success:false,error:{code,message}}); const token=(id:string)=>crypto.createHash('sha256').update(id).digest('hex');
app.setErrorHandler((e:any,_q,r)=>r.status(e.statusCode||500).send(fail(e.code==='P2002'?'CONFLICT':'SERVER_ERROR',e.message==='Unauthorized'?'Authentication required':'Something went wrong.')));
async function context(req:any,reply:any){try{const p:any=await req.jwtVerify(); const membership=await db.membership.findUnique({where:{userId_organizationId:{userId:p.userId,organizationId:p.organizationId}},include:{user:true,organization:true}}); if(!membership||membership.status!==MemberStatus.ACTIVE)throw Error(); return membership;}catch{reply.status(401).send(fail('UNAUTHORIZED','Authentication required.')); return null;}}
function guard(p:string){return async(q:any,r:any)=>{const m=await context(q,r); if(!m)return; if(!hasPermission(m.role,p)){r.status(403).send(fail('FORBIDDEN','You do not have permission to perform this action.'));return;} q.member=m;};}
async function activity(org:string,actor:string,action:string,entityType:string,entityId?:string){await db.activityLog.create({data:{organizationId:org,actorUserId:actor,action,entityType,entityId}})}
function teamScope(m:any){return m.role==='CEO'?{}:m.role==='MANAGER'?{managerId:m.userId}:m.role==='TEAM_LEAD'?{teamLeadId:m.userId}:{members:{some:{userId:m.userId}}};}
app.post('/api/v1/auth/register',async(q,r)=>{const v=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8),organizationName:z.string().min(2)}).parse(q.body); const slug=v.organizationName.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+crypto.randomBytes(2).toString('hex'); const user=await db.user.create({data:{name:v.name,email:v.email.toLowerCase(),passwordHash:await bcrypt.hash(v.password,12)}}); const org=await db.organization.create({data:{name:v.organizationName,slug}}); await db.membership.create({data:{userId:user.id,organizationId:org.id,role:Role.CEO}}); const session=app.jwt.sign({userId:user.id,organizationId:org.id}); r.setCookie('dm_session',session,sessionCookie); return ok({user:{id:user.id,name:user.name,email:user.email},organization:org});});
app.post('/api/v1/auth/login',async(q,r)=>{const v=z.object({email:z.string().email(),password:z.string()}).parse(q.body); const user=await db.user.findUnique({where:{email:v.email.toLowerCase()},include:{memberships:{include:{organization:true}}}}); if(!user||!await bcrypt.compare(v.password,user.passwordHash))return r.status(401).send(fail('INVALID_CREDENTIALS','Invalid email or password.')); const m=user.memberships.find(x=>x.status===MemberStatus.ACTIVE); if(!m)return r.status(403).send(fail('ACCOUNT_INACTIVE','No active organization membership.')); r.setCookie('dm_session',app.jwt.sign({userId:user.id,organizationId:m.organizationId}),sessionCookie);return ok({user:{id:user.id,name:user.name,email:user.email},organization:m.organization,role:m.role});});
app.post('/api/v1/auth/logout',async(_q,r)=>{r.clearCookie('dm_session',sessionCookie);return ok({});});
app.post('/api/v1/auth/forgot-password',async(q)=>{const v=z.object({email:z.string().email()}).parse(q.body);const user=await db.user.findUnique({where:{email:v.email.toLowerCase()}});if(!user)return ok({message:'If an account exists, reset instructions have been sent.'});const raw=crypto.randomBytes(32).toString('base64url');await db.passwordResetToken.create({data:{userId:user.id,tokenHash:token(raw),expiresAt:new Date(Date.now()+3600000)}});return ok({message:'If an account exists, reset instructions have been sent.',developmentResetToken:raw});});
app.post('/api/v1/auth/reset-password',async(q,r)=>{const v=z.object({token:z.string(),password:z.string().min(8)}).parse(q.body);const reset=await db.passwordResetToken.findUnique({where:{tokenHash:token(v.token)}});if(!reset||reset.usedAt||reset.expiresAt<new Date())return r.status(422).send(fail('INVALID_RESET_TOKEN','This reset link is invalid or expired.'));await db.$transaction([db.user.update({where:{id:reset.userId},data:{passwordHash:await bcrypt.hash(v.password,12)}}),db.passwordResetToken.update({where:{id:reset.id},data:{usedAt:new Date()}})]);return ok({message:'Password updated. You can now sign in.'});});
app.get('/api/v1/me',async(q,r)=>{const m=await context(q,r);if(!m)return;return ok({user:m.user,organization:m.organization,role:m.role,permissions:rolePermissions[m.role]||[]});});
app.get('/api/v1/dashboard', {preHandler:guard('analytics.organization')},async(q:any)=>{const org=q.member.organizationId;const [members,active,teams,invites,activities]=await Promise.all([db.membership.count({where:{organizationId:org}}),db.membership.count({where:{organizationId:org,status:MemberStatus.ACTIVE}}),db.team.count({where:{organizationId:org}}),db.invitation.count({where:{organizationId:org,status:InvitationStatus.PENDING}}),db.activityLog.findMany({where:{organizationId:org},take:8,orderBy:{createdAt:'desc'},include:{actor:true}})]);return ok({members,active,teams,invites,status:q.member.organization.status,activities});});
app.get('/api/v1/members',{preHandler:guard('users.view')},async(q:any)=>{const all=await db.membership.findMany({where:{organizationId:q.member.organizationId,status:{not:MemberStatus.DEACTIVATED}},include:{user:true,reportsTo:{select:{id:true,name:true,email:true}}},orderBy:{joinedAt:'asc'}});if(q.member.role==='CEO')return ok(all.filter((m:any)=>m.userId!==q.member.userId));const visible=new Set(all.filter((m:any)=>m.reportsToId===q.member.userId).map((m:any)=>m.userId));if(q.member.role==='MANAGER')for(const m of all)if(m.reportsToId&&visible.has(m.reportsToId))visible.add(m.userId);return ok(all.filter((m:any)=>visible.has(m.userId)));});
app.patch('/api/v1/members/:id',{preHandler:guard('users.update')},async(q:any,r)=>{const v=z.object({role:z.nativeEnum(Role).optional(),status:z.nativeEnum(MemberStatus).optional()}).parse(q.body);const target=await db.membership.findFirst({where:{id:q.params.id,organizationId:q.member.organizationId}});if(!target)return r.status(404).send(fail('NOT_FOUND','Member not found.'));if(target.role===Role.CEO||target.userId===q.member.userId)return r.status(403).send(fail('FORBIDDEN','The CEO role and your own access cannot be changed here.'));if(v.role&&!canAssignRole(q.member.role,v.role))return r.status(403).send(fail('FORBIDDEN','You cannot assign that role.'));const updated=await db.membership.update({where:{id:target.id},data:v});await activity(q.member.organizationId,q.member.userId,v.role?'ROLE_CHANGED':v.status==='DEACTIVATED'?'USER_DEACTIVATED':'USER_REACTIVATED','membership',target.id);return ok(updated);});
app.get('/api/v1/teams',{preHandler:guard('teams.view')},async(q:any)=>ok(await db.team.findMany({where:{organizationId:q.member.organizationId,...teamScope(q.member)},include:{teamLead:true,manager:true,_count:{select:{members:true}}},orderBy:{createdAt:'desc'}})));
app.post('/api/v1/teams',{preHandler:guard('teams.create')},async(q:any)=>{const v=z.object({name:z.string().min(2),description:z.string().optional(),teamLeadId:z.string().optional(),managerId:z.string().optional()}).parse(q.body);if(v.teamLeadId&&!await db.membership.findFirst({where:{organizationId:q.member.organizationId,userId:v.teamLeadId,status:MemberStatus.ACTIVE}}))throw Object.assign(new Error('Team lead must be an active member.'),{statusCode:422});const managerId=q.member.role==='MANAGER'?q.member.userId:v.managerId;const team=await db.team.create({data:{...v,managerId,organizationId:q.member.organizationId}});await activity(q.member.organizationId,q.member.userId,'TEAM_CREATED','team',team.id);return ok(team);});
app.get('/api/v1/teams/:id',{preHandler:guard('teams.view')},async(q:any,r)=>{const team=await db.team.findFirst({where:{id:q.params.id,organizationId:q.member.organizationId,...teamScope(q.member)},include:{teamLead:true,manager:true,members:{include:{user:true}}}});return team?ok(team):r.status(404).send(fail('NOT_FOUND','Team not found.'));});
app.post('/api/v1/teams/:id/members',{preHandler:guard('teams.members.manage')},async(q:any,r)=>{const v=z.object({userId:z.string()}).parse(q.body);const team=await db.team.findFirst({where:{id:q.params.id,organizationId:q.member.organizationId,...teamScope(q.member)}});const m=await db.membership.findFirst({where:{organizationId:q.member.organizationId,userId:v.userId,status:MemberStatus.ACTIVE,role:{in:[Role.TEAM_LEAD,Role.EMPLOYEE]}}});if(!team||!m)return r.status(404).send(fail('NOT_FOUND','Team or eligible member not found.'));return ok(await db.teamMember.upsert({where:{teamId_userId:{teamId:team.id,userId:v.userId}},create:{teamId:team.id,userId:v.userId},update:{}}));});
app.get('/api/v1/invitations',{preHandler:guard('users.invite')},async(q:any)=>ok(await db.invitation.findMany({where:{organizationId:q.member.organizationId},orderBy:{createdAt:'desc'}})));
app.post('/api/v1/invitations',{preHandler:guard('users.invite')},async(q:any,r)=>{const v=z.object({email:z.string().email(),role:z.nativeEnum(Role),teamId:z.string().optional()}).parse(q.body);if(!canAssignRole(q.member.role,v.role))return r.status(403).send(fail('FORBIDDEN','You cannot invite a member with that role.'));if(v.teamId&&!await db.team.findFirst({where:{id:v.teamId,organizationId:q.member.organizationId}}))return r.status(422).send(fail('INVALID_TEAM','The selected team is not in this organization.'));const raw=crypto.randomBytes(32).toString('base64url');const invite=await db.invitation.create({data:{organizationId:q.member.organizationId,email:v.email.toLowerCase(),role:v.role,teamId:v.teamId,invitedById:q.member.userId,tokenHash:token(raw),expiresAt:new Date(Date.now()+7*86400000)}});await activity(q.member.organizationId,q.member.userId,'USER_INVITED','invitation',invite.id);return ok({...invite,invitationToken:raw});});
app.post('/api/v1/invitations/accept',async(q,r)=>{const v=z.object({token:z.string(),name:z.string().min(2),password:z.string().min(8)}).parse(q.body);const invite=await db.invitation.findUnique({where:{tokenHash:token(v.token)}});if(!invite||invite.status!==InvitationStatus.PENDING||invite.expiresAt<new Date())return r.status(422).send(fail('INVALID_INVITATION','This invitation is invalid or expired.'));let user=await db.user.findUnique({where:{email:invite.email}});if(!user)user=await db.user.create({data:{name:v.name,email:invite.email,passwordHash:await bcrypt.hash(v.password,12)}});else await db.user.update({where:{id:user.id},data:{name:v.name}});await db.$transaction([db.membership.upsert({where:{userId_organizationId:{userId:user.id,organizationId:invite.organizationId}},create:{userId:user.id,organizationId:invite.organizationId,role:invite.role,reportsToId:invite.invitedById},update:{role:invite.role,status:MemberStatus.ACTIVE,reportsToId:invite.invitedById}}),db.invitation.update({where:{id:invite.id},data:{status:InvitationStatus.ACCEPTED}})]);if(invite.teamId)await db.teamMember.upsert({where:{teamId_userId:{teamId:invite.teamId,userId:user.id}},create:{teamId:invite.teamId,userId:user.id},update:{}});await activity(invite.organizationId,user.id,'INVITATION_ACCEPTED','invitation',invite.id);r.setCookie('dm_session',app.jwt.sign({userId:user.id,organizationId:invite.organizationId}),sessionCookie);return ok({message:'Invitation accepted.'});});
app.patch('/api/v1/organization',{preHandler:guard('organization.update')},async(q:any)=>{const v=z.object({name:z.string().min(2).optional(),industry:z.string().optional(),timezone:z.string().optional(),currency:z.string().optional(),logoUrl:z.string().url().optional()}).parse(q.body);const org=await db.organization.update({where:{id:q.member.organizationId},data:v});await activity(org.id,q.member.userId,'ORGANIZATION_UPDATED','organization',org.id);return ok(org);});
app.patch('/api/v1/profile',async(q,r)=>{const m=await context(q,r);if(!m)return;const v=z.object({name:z.string().min(2).optional(),phone:z.string().optional(),jobTitle:z.string().optional(),bio:z.string().max(500).optional(),timezone:z.string().optional()}).parse(q.body);return ok(await db.user.update({where:{id:m.userId},data:v}));});
const pageQuery=z.object({page:z.coerce.number().int().min(1).default(1),page_size:z.coerce.number().int().min(1).max(100).default(20),search:z.string().optional(),status:z.string().optional(),client_id:z.string().optional(),type:z.string().optional()});
const clientInput=z.object({name:z.string().trim().min(2).max(160),companyName:z.string().trim().max(160).nullish(),industry:z.string().trim().max(80).nullish(),websiteUrl:z.string().url().nullish().or(z.literal('')),primaryEmail:z.string().email().nullish().or(z.literal('')),primaryPhone:z.string().max(40).nullish(),addressLine1:z.string().max(200).nullish(),addressLine2:z.string().max(200).nullish(),city:z.string().max(100).nullish(),state:z.string().max(100).nullish(),postalCode:z.string().max(30).nullish(),countryCode:z.string().length(2).transform(x=>x.toUpperCase()).nullish(),timezone:z.string().max(80).nullish(),status:z.enum(['ACTIVE','INACTIVE']).optional(),ownerUserId:z.string().nullish(),notes:z.string().max(10000).nullish(),primaryContact:z.object({name:z.string().min(2),email:z.string().email().nullish().or(z.literal('')),phone:z.string().max(40).nullish(),jobTitle:z.string().max(100).nullish()}).optional()});
const campaignInput=z.object({clientId:z.string(),name:z.string().trim().min(2).max(180),description:z.string().max(10000).nullish(),campaignType:z.enum(['SOCIAL_MEDIA','SEO','PAID_ADVERTISING','CONTENT_MARKETING','EMAIL_MARKETING','BRANDING','WEBSITE','INFLUENCER_MARKETING','OTHER']),objectiveSummary:z.string().max(1000).nullish(),startDate:z.coerce.date().nullish(),endDate:z.coerce.date().nullish(),budgetAmount:z.coerce.number().min(0).nullish(),objectives:z.array(z.object({title:z.string().min(2),description:z.string().nullish(),metricType:z.string().nullish(),targetValue:z.coerce.number().nonnegative().nullish(),unit:z.string().nullish()})).optional(),teamIds:z.array(z.string()).optional()});
function resourceScope(m:any){if(m.role==='CEO')return {};return {teamAssignments:{some:{removedAt:null,team:{OR:[{managerId:m.userId},{teamLeadId:m.userId},{members:{some:{userId:m.userId}}}]}}}};}
async function visibleCampaign(m:any,id:string){return db.campaign.findFirst({where:{id,organizationId:m.organizationId,...resourceScope(m)}})}
async function visibleClient(m:any,id:string){return db.client.findFirst({where:{id,organizationId:m.organizationId,...(m.role==='CEO'?{}:{campaigns:{some:resourceScope(m)}})}})}
async function clientEvent(org:string,clientId:string,actor:string,type:string,description:string){return db.clientActivity.create({data:{organizationId:org,clientId,actorUserId:actor,activityType:type,description}})}
async function campaignEvent(org:string,campaignId:string,actor:string,type:string,description:string){return db.campaignActivity.create({data:{organizationId:org,campaignId,actorUserId:actor,activityType:type,description}})}

app.get('/api/v1/clients',{preHandler:guard('clients.view')},async(q:any)=>{const v=pageQuery.parse(q.query),org=q.member.organizationId;const where:any={organizationId:org,...(q.member.role==='CEO'?{}:{campaigns:{some:resourceScope(q.member)}})};if(v.status)where.status=v.status;else where.status={not:'ARCHIVED'};if(v.search)where.OR=['name','companyName','primaryEmail','websiteUrl'].map(k=>({[k]:{contains:v.search,mode:'insensitive'}}));const [data,total,active,inactive,archived]=await Promise.all([db.client.findMany({where,skip:(v.page-1)*v.page_size,take:v.page_size,orderBy:{updatedAt:'desc'},include:{owner:{select:{id:true,name:true}},_count:{select:{campaigns:true}}}}),db.client.count({where}),db.client.count({where:{...where,status:'ACTIVE'}}),db.client.count({where:{...where,status:'INACTIVE'}}),db.client.count({where:{...where,status:'ARCHIVED'}})]);return {...ok(data),pagination:{page:v.page,page_size:v.page_size,total,total_pages:Math.ceil(total/v.page_size)},summary:{active,inactive,archived}}});
app.post('/api/v1/clients',{preHandler:guard('clients.create')},async(q:any,r)=>{const v=clientInput.parse(q.body),org=q.member.organizationId;if(v.ownerUserId&&!await db.membership.findFirst({where:{organizationId:org,userId:v.ownerUserId,status:'ACTIVE'}}))return r.status(422).send(fail('INVALID_CEO','Owner must be an active organization member.'));const duplicate=await db.client.findFirst({where:{organizationId:org,name:{equals:v.name,mode:'insensitive'},status:{not:'ARCHIVED'}}});if(duplicate)return r.status(409).send(fail('DUPLICATE_CLIENT','An active client with this name already exists.'));const {primaryContact,...data}=v;const created=await db.$transaction(async tx=>{const client=await tx.client.create({data:{...data,websiteUrl:data.websiteUrl||null,primaryEmail:data.primaryEmail||null,organizationId:org,createdBy:q.member.userId}});if(primaryContact)await tx.clientContact.create({data:{...primaryContact,email:primaryContact.email||null,organizationId:org,clientId:client.id,isPrimary:true}});await tx.clientActivity.create({data:{organizationId:org,clientId:client.id,actorUserId:q.member.userId,activityType:'CLIENT_CREATED',description:'Client created'}});return client});return r.status(201).send(ok(created));});
app.get('/api/v1/clients/:id',{preHandler:guard('clients.view')},async(q:any,r)=>{if(!await visibleClient(q.member,q.params.id))return r.status(404).send(fail('NOT_FOUND','Client not found.'));return ok(await db.client.findFirst({where:{id:q.params.id,organizationId:q.member.organizationId},include:{owner:{select:{id:true,name:true}},contacts:{orderBy:[{isPrimary:'desc'},{createdAt:'asc'}]},campaigns:{where:{archivedAt:null},include:{teamAssignments:{where:{removedAt:null},include:{team:true}}},orderBy:{updatedAt:'desc'}},activities:{take:30,orderBy:{createdAt:'desc'},include:{actor:{select:{name:true}}}}}}));});
app.patch('/api/v1/clients/:id',{preHandler:guard('clients.update')},async(q:any,r)=>{const current=await visibleClient(q.member,q.params.id);if(!current)return r.status(404).send(fail('NOT_FOUND','Client not found.'));const v=clientInput.partial().omit({primaryContact:true}).parse(q.body);if(v.ownerUserId&&!await db.membership.findFirst({where:{organizationId:q.member.organizationId,userId:v.ownerUserId}}))return r.status(422).send(fail('INVALID_CEO','Owner must belong to this organization.'));const updated=await db.client.update({where:{id:current.id},data:v});await clientEvent(q.member.organizationId,current.id,q.member.userId,'CLIENT_UPDATED','Client details updated');return ok(updated);});
app.post('/api/v1/clients/:id/archive',{preHandler:guard('clients.archive')},async(q:any,r)=>{const c=await visibleClient(q.member,q.params.id);if(!c)return r.status(404).send(fail('NOT_FOUND','Client not found.'));const updated=await db.client.update({where:{id:c.id},data:{status:'ARCHIVED',archivedAt:new Date()}});await clientEvent(q.member.organizationId,c.id,q.member.userId,'CLIENT_ARCHIVED','Client archived');return ok(updated);});
app.post('/api/v1/clients/:id/restore',{preHandler:guard('clients.archive')},async(q:any,r)=>{const c=await db.client.findFirst({where:{id:q.params.id,organizationId:q.member.organizationId}});if(!c)return r.status(404).send(fail('NOT_FOUND','Client not found.'));const updated=await db.client.update({where:{id:c.id},data:{status:'ACTIVE',archivedAt:null}});await clientEvent(q.member.organizationId,c.id,q.member.userId,'CLIENT_RESTORED','Client restored');return ok(updated);});
const contactInput=z.object({name:z.string().min(2),email:z.string().email().nullish().or(z.literal('')),phone:z.string().max(40).nullish(),jobTitle:z.string().max(100).nullish(),isPrimary:z.boolean().optional()});
app.get('/api/v1/clients/:id/contacts',{preHandler:guard('clients.view')},async(q:any,r)=>!await visibleClient(q.member,q.params.id)?r.status(404).send(fail('NOT_FOUND','Client not found.')):ok(await db.clientContact.findMany({where:{clientId:q.params.id,organizationId:q.member.organizationId},orderBy:{isPrimary:'desc'}})));
app.post('/api/v1/clients/:id/contacts',{preHandler:guard('contacts.manage')},async(q:any,r)=>{if(!await visibleClient(q.member,q.params.id))return r.status(404).send(fail('NOT_FOUND','Client not found.'));const v=contactInput.parse(q.body),contact=await db.$transaction(async tx=>{if(v.isPrimary)await tx.clientContact.updateMany({where:{clientId:q.params.id},data:{isPrimary:false}});return tx.clientContact.create({data:{...v,email:v.email||null,organizationId:q.member.organizationId,clientId:q.params.id}})});await clientEvent(q.member.organizationId,q.params.id,q.member.userId,'CONTACT_ADDED',`Contact ${contact.name} added`);return r.status(201).send(ok(contact));});
app.patch('/api/v1/clients/:id/contacts/:contactId',{preHandler:guard('contacts.manage')},async(q:any,r)=>{const c=await db.clientContact.findFirst({where:{id:q.params.contactId,clientId:q.params.id,organizationId:q.member.organizationId}});if(!c)return r.status(404).send(fail('NOT_FOUND','Contact not found.'));const v=contactInput.partial().parse(q.body);const updated=await db.$transaction(async tx=>{if(v.isPrimary)await tx.clientContact.updateMany({where:{clientId:q.params.id},data:{isPrimary:false}});return tx.clientContact.update({where:{id:c.id},data:v})});await clientEvent(q.member.organizationId,q.params.id,q.member.userId,'CONTACT_UPDATED',`Contact ${updated.name} updated`);return ok(updated);});
app.post('/api/v1/clients/:id/contacts/:contactId/set-primary',{preHandler:guard('contacts.manage')},async(q:any,r)=>{const c=await db.clientContact.findFirst({where:{id:q.params.contactId,clientId:q.params.id,organizationId:q.member.organizationId}});if(!c)return r.status(404).send(fail('NOT_FOUND','Contact not found.'));await db.$transaction([db.clientContact.updateMany({where:{clientId:q.params.id},data:{isPrimary:false}}),db.clientContact.update({where:{id:c.id},data:{isPrimary:true}})]);return ok({id:c.id,isPrimary:true});});
app.delete('/api/v1/clients/:id/contacts/:contactId',{preHandler:guard('contacts.manage')},async(q:any,r)=>{const c=await db.clientContact.findFirst({where:{id:q.params.contactId,clientId:q.params.id,organizationId:q.member.organizationId}});if(!c)return r.status(404).send(fail('NOT_FOUND','Contact not found.'));await db.clientContact.delete({where:{id:c.id}});await clientEvent(q.member.organizationId,q.params.id,q.member.userId,'CONTACT_REMOVED',`Contact ${c.name} removed`);return ok({});});
app.get('/api/v1/clients/:id/activities',{preHandler:guard('clients.view')},async(q:any,r)=>!await visibleClient(q.member,q.params.id)?r.status(404).send(fail('NOT_FOUND','Client not found.')):ok(await db.clientActivity.findMany({where:{clientId:q.params.id,organizationId:q.member.organizationId},orderBy:{createdAt:'desc'},take:50,include:{actor:{select:{name:true}}}})));
app.post('/api/v1/clients/:id/activities',{preHandler:guard('clients.update')},async(q:any,r)=>{if(!await visibleClient(q.member,q.params.id))return r.status(404).send(fail('NOT_FOUND','Client not found.'));const v=z.object({description:z.string().min(1).max(5000)}).parse(q.body);return r.status(201).send(ok(await clientEvent(q.member.organizationId,q.params.id,q.member.userId,'NOTE_ADDED',v.description)));});

app.get('/api/v1/campaigns',{preHandler:guard('campaigns.view')},async(q:any)=>{const v=pageQuery.parse(q.query),where:any={organizationId:q.member.organizationId,archivedAt:null,...resourceScope(q.member)};if(v.status)where.status=v.status;if(v.client_id)where.clientId=v.client_id;if(v.type)where.campaignType=v.type;if(v.search)where.OR=[{name:{contains:v.search,mode:'insensitive'}},{client:{name:{contains:v.search,mode:'insensitive'}}}];const [data,total]=await Promise.all([db.campaign.findMany({where,skip:(v.page-1)*v.page_size,take:v.page_size,orderBy:{updatedAt:'desc'},include:{client:{select:{id:true,name:true}},teamAssignments:{where:{removedAt:null},include:{team:true}},_count:{select:{objectives:true}}}}),db.campaign.count({where})]);return {...ok(data),pagination:{page:v.page,page_size:v.page_size,total,total_pages:Math.ceil(total/v.page_size)}}});
app.post('/api/v1/campaigns',{preHandler:guard('campaigns.create')},async(q:any,r)=>{const v=campaignInput.parse(q.body),org=q.member.organizationId;const client=await db.client.findFirst({where:{id:v.clientId,organizationId:org,status:{not:'ARCHIVED'}}});if(!client)return r.status(422).send(fail('INVALID_CLIENT','Client was not found or is archived.'));if(v.teamIds?.length&&await db.team.count({where:{id:{in:v.teamIds},organizationId:org}})!==new Set(v.teamIds).size)return r.status(422).send(fail('INVALID_TEAM','Every team must belong to this organization.'));const {objectives=[],teamIds=[],...data}=v;const campaign=await db.$transaction(async tx=>{const c=await tx.campaign.create({data:{...data,organizationId:org,currencyCode:q.member.organization.currency,createdBy:q.member.userId,updatedBy:q.member.userId}});if(objectives.length)await tx.campaignObjective.createMany({data:objectives.map(o=>({...o,organizationId:org,campaignId:c.id}))});if(teamIds.length)await tx.campaignTeamAssignment.createMany({data:teamIds.map((teamId,i)=>({organizationId:org,campaignId:c.id,teamId,assignedBy:q.member.userId,assignmentRole:i?'SUPPORTING':'PRIMARY'}))});await tx.campaignActivity.create({data:{organizationId:org,campaignId:c.id,actorUserId:q.member.userId,activityType:'CAMPAIGN_CREATED',description:'Campaign created'}});return c});return r.status(201).send(ok(campaign));});
app.get('/api/v1/campaigns/:id',{preHandler:guard('campaigns.view')},async(q:any,r)=>{if(!await visibleCampaign(q.member,q.params.id))return r.status(404).send(fail('NOT_FOUND','Campaign not found.'));return ok(await db.campaign.findFirst({where:{id:q.params.id,organizationId:q.member.organizationId},include:{client:true,objectives:true,teamAssignments:{where:{removedAt:null},include:{team:true}},activities:{take:50,orderBy:{createdAt:'desc'},include:{actor:{select:{name:true}}}}}}));});
app.patch('/api/v1/campaigns/:id',{preHandler:guard('campaigns.update')},async(q:any,r)=>{const c=await visibleCampaign(q.member,q.params.id);if(!c)return r.status(404).send(fail('NOT_FOUND','Campaign not found.'));const v=campaignInput.partial().omit({objectives:true,teamIds:true}).parse(q.body);if(v.clientId&&!await db.client.findFirst({where:{id:v.clientId,organizationId:q.member.organizationId,status:{not:'ARCHIVED'}}}))return r.status(422).send(fail('INVALID_CLIENT','Client not found.'));const updated=await db.campaign.update({where:{id:c.id},data:{...v,updatedBy:q.member.userId}});await campaignEvent(q.member.organizationId,c.id,q.member.userId,'CAMPAIGN_UPDATED','Campaign details updated');return ok(updated);});
const transitions:any={DRAFT:['PLANNED','CANCELLED'],PLANNED:['ACTIVE','PAUSED','CANCELLED'],ACTIVE:['PAUSED','COMPLETED','CANCELLED'],PAUSED:['ACTIVE','CANCELLED'],COMPLETED:[],CANCELLED:[]};
app.post('/api/v1/campaigns/:id/status',{preHandler:guard('campaigns.status')},async(q:any,r)=>{const c:any=await visibleCampaign(q.member,q.params.id);if(!c)return r.status(404).send(fail('NOT_FOUND','Campaign not found.'));const {status}=z.object({status:z.enum(['DRAFT','PLANNED','ACTIVE','PAUSED','COMPLETED','CANCELLED'])}).parse(q.body);if(!transitions[c.status].includes(status))return r.status(422).send(fail('INVALID_STATUS_TRANSITION',`${c.status} cannot transition to ${status}.`));const updated=await db.campaign.update({where:{id:c.id},data:{status,updatedBy:q.member.userId}});await campaignEvent(q.member.organizationId,c.id,q.member.userId,'STATUS_CHANGED',`${c.status} changed to ${status}`);return ok(updated);});
const objectiveInput=z.object({title:z.string().min(2),description:z.string().nullish(),metricType:z.string().nullish(),targetValue:z.coerce.number().nonnegative().nullish(),unit:z.string().nullish()});
app.get('/api/v1/campaigns/:id/objectives',{preHandler:guard('campaigns.view')},async(q:any,r)=>!await visibleCampaign(q.member,q.params.id)?r.status(404).send(fail('NOT_FOUND','Campaign not found.')):ok(await db.campaignObjective.findMany({where:{campaignId:q.params.id,organizationId:q.member.organizationId}})));
app.post('/api/v1/campaigns/:id/objectives',{preHandler:guard('campaigns.update')},async(q:any,r)=>{if(!await visibleCampaign(q.member,q.params.id))return r.status(404).send(fail('NOT_FOUND','Campaign not found.'));const v=objectiveInput.parse(q.body);return r.status(201).send(ok(await db.campaignObjective.create({data:{...v,campaignId:q.params.id,organizationId:q.member.organizationId}})));});
app.patch('/api/v1/campaigns/:id/objectives/:objectiveId',{preHandler:guard('campaigns.update')},async(q:any,r)=>{const o=await db.campaignObjective.findFirst({where:{id:q.params.objectiveId,campaignId:q.params.id,organizationId:q.member.organizationId}});if(!o||!await visibleCampaign(q.member,q.params.id))return r.status(404).send(fail('NOT_FOUND','Objective not found.'));return ok(await db.campaignObjective.update({where:{id:o.id},data:objectiveInput.partial().parse(q.body)}));});
app.delete('/api/v1/campaigns/:id/objectives/:objectiveId',{preHandler:guard('campaigns.update')},async(q:any,r)=>{const o=await db.campaignObjective.findFirst({where:{id:q.params.objectiveId,campaignId:q.params.id,organizationId:q.member.organizationId}});if(!o||!await visibleCampaign(q.member,q.params.id))return r.status(404).send(fail('NOT_FOUND','Objective not found.'));await db.campaignObjective.delete({where:{id:o.id}});return ok({});});
app.get('/api/v1/campaigns/:id/teams',{preHandler:guard('campaigns.view')},async(q:any,r)=>!await visibleCampaign(q.member,q.params.id)?r.status(404).send(fail('NOT_FOUND','Campaign not found.')):ok(await db.campaignTeamAssignment.findMany({where:{campaignId:q.params.id,organizationId:q.member.organizationId,removedAt:null},include:{team:true}})));
app.post('/api/v1/campaigns/:id/teams',{preHandler:guard('campaigns.teams')},async(q:any,r)=>{const v=z.object({teamId:z.string(),assignmentRole:z.enum(['PRIMARY','SUPPORTING']).default('SUPPORTING')}).parse(q.body);if(!await visibleCampaign(q.member,q.params.id)||!await db.team.findFirst({where:{id:v.teamId,organizationId:q.member.organizationId}}))return r.status(404).send(fail('NOT_FOUND','Campaign or team not found.'));const a=await db.campaignTeamAssignment.upsert({where:{campaignId_teamId:{campaignId:q.params.id,teamId:v.teamId}},create:{...v,campaignId:q.params.id,organizationId:q.member.organizationId,assignedBy:q.member.userId},update:{removedAt:null,assignmentRole:v.assignmentRole,assignedBy:q.member.userId,assignedAt:new Date()}});await campaignEvent(q.member.organizationId,q.params.id,q.member.userId,'TEAM_ASSIGNED','Team assigned');return r.status(201).send(ok(a));});
app.delete('/api/v1/campaigns/:id/teams/:teamId',{preHandler:guard('campaigns.teams')},async(q:any,r)=>{const a=await db.campaignTeamAssignment.findFirst({where:{campaignId:q.params.id,teamId:q.params.teamId,organizationId:q.member.organizationId,removedAt:null}});if(!a)return r.status(404).send(fail('NOT_FOUND','Assignment not found.'));await db.campaignTeamAssignment.update({where:{id:a.id},data:{removedAt:new Date()}});await campaignEvent(q.member.organizationId,q.params.id,q.member.userId,'TEAM_REMOVED','Team assignment removed');return ok({});});
app.get('/api/v1/campaigns/:id/activities',{preHandler:guard('campaigns.view')},async(q:any,r)=>!await visibleCampaign(q.member,q.params.id)?r.status(404).send(fail('NOT_FOUND','Campaign not found.')):ok(await db.campaignActivity.findMany({where:{campaignId:q.params.id,organizationId:q.member.organizationId},orderBy:{createdAt:'desc'},take:50})));
app.get('/api/v1/dashboard/summary',{preHandler:guard('organization.view')},async(q:any)=>{const org=q.member.organizationId,cScope:any=q.member.role==='CEO'?{}:{campaigns:{some:resourceScope(q.member)}},campaignScope:any=resourceScope(q.member),soon=new Date(Date.now()+30*86400000);const [totalClients,activeClients,totalCampaigns,activeCampaigns,plannedCampaigns,endingSoon,recentClients,recentCampaigns]=await Promise.all([db.client.count({where:{organizationId:org,status:{not:'ARCHIVED'},...cScope}}),db.client.count({where:{organizationId:org,status:'ACTIVE',...cScope}}),db.campaign.count({where:{organizationId:org,archivedAt:null,...campaignScope}}),db.campaign.count({where:{organizationId:org,status:'ACTIVE',...campaignScope}}),db.campaign.count({where:{organizationId:org,status:'PLANNED',...campaignScope}}),db.campaign.count({where:{organizationId:org,status:{in:['ACTIVE','PLANNED']},endDate:{lte:soon,gte:new Date()},...campaignScope}}),db.client.findMany({where:{organizationId:org,...cScope},take:5,orderBy:{updatedAt:'desc'},select:{id:true,name:true,status:true,updatedAt:true}}),db.campaign.findMany({where:{organizationId:org,...campaignScope},take:5,orderBy:{updatedAt:'desc'},select:{id:true,name:true,status:true,updatedAt:true}})]);return ok({totalClients,activeClients,totalCampaigns,activeCampaigns,plannedCampaigns,endingSoon,recentClients,recentCampaigns});});

await registerTaskRoutes(app,db,guard,ok,fail);
await registerPortalRoutes(app,db,context);
await registerAnalyticsRoutes(app,db,context);

app.listen({port:Number(process.env.PORT||4000),host:'0.0.0.0'});
