"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { Layout } from "../../../components/Layout";
import { TaskTimer } from "../../../components/TaskTimer";
import { api, label, request, useWorkspace } from "../../../components/useWorkspace";

export default function TaskDetail() {
  const me = useWorkspace(), { id } = useParams(), [task, setTask] = useState<any>(), [error, setError] = useState(""), [comment, setComment] = useState(""), [submission, setSubmission] = useState("");
  const load = useCallback(async () => { const r = await fetch(`${api}/tasks/${id}`, { credentials: "include" }), x = await r.json(); x.success ? setTask(x.data) : setError(x.error.message); }, [id]);
  useEffect(() => { load(); }, [load]);
  async function act(path: string, body: any = {}) { try { setError(""); await request(`/tasks/${id}${path}`, { method: "POST", body: JSON.stringify(body) }); setComment(""); setSubmission(""); await load(); } catch (e: any) { setError(e.message); } }
  async function toggle(s: any) { try { await request(`/tasks/${id}/subtasks/${s.id}`, { method: "PATCH", body: JSON.stringify({ completed: !s.completed }) }); load(); } catch (e: any) { setError(e.message); } }
  async function addSubtask(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = e.currentTarget; try { await request(`/tasks/${id}/subtasks`, { method: "POST", body: JSON.stringify(Object.fromEntries(new FormData(f))) }); f.reset(); load(); } catch (e: any) { setError(e.message); } }
  if (!me || (!task && !error)) return <div className="loading">Loading task…</div>;
  if (!task) return <Layout me={me}><section className="card error-state">{error}</section></Layout>;
  const manager = ["CEO", "MANAGER", "TEAM_LEAD"].includes(me.role), assigned = task.assignees.some((a: any) => a.userId === me.user.id);
  return <Layout me={me}>
    <header className="page-head"><div><p className="eyebrow">{task.campaign.client.name} / {task.campaign.name}</p><h1>{task.title}</h1><p><span className={`pill status-${task.status.toLowerCase()}`}>{label(task.status)}</span> <span className={`pill priority-${task.priority.toLowerCase()}`}>{label(task.priority)}</span> · Due {task.dueDate ? new Date(task.dueDate).toLocaleString() : "not set"}</p></div>{manager && <Link className="button secondary" href={`/tasks/${id}/edit`}>Edit</Link>}</header>
    {error && <p className="form-error" role="alert">{error}</p>}
    <TaskTimer task={task} me={me} onChanged={load} />
    <section className="card"><div className="card-title"><div><h2>Progress</h2><p>Checklist completion supports the task’s execution record.</p></div><strong>{task.progressPercentage}%</strong></div><div className="progress large"><span style={{ width: `${task.progressPercentage}%` }} /></div>{(assigned || manager) && !["COMPLETED", "CANCELLED"].includes(task.status) && <input aria-label="Task progress" type="range" min="0" max="100" value={task.progressPercentage} onChange={e => setTask({ ...task, progressPercentage: Number(e.target.value) })} onMouseUp={e => act("/progress", { progress: Number((e.target as HTMLInputElement).value) })} />}</section>
    <div className="detail-grid"><section className="card"><h2>Overview</h2><p>{task.description || "No description provided."}</p><dl><dt>Type</dt><dd>{label(task.taskType)}</dd><dt>Campaign</dt><dd><Link className="record-link" href={`/campaigns/${task.campaign.id}`}>{task.campaign.name}</Link></dd><dt>Client</dt><dd>{task.campaign.client.name}</dd><dt>Team</dt><dd>{task.team.name}</dd><dt>Assignee</dt><dd>{task.assignees.find((a: any) => a.assignmentType === "PRIMARY")?.user.name || "Unassigned"}</dd><dt>Schedule</dt><dd>{task.startDate ? new Date(task.startDate).toLocaleDateString() : "Open"} – {task.dueDate ? new Date(task.dueDate).toLocaleString() : "Open"}</dd><dt>Created by</dt><dd>{task.creator.name} · {new Date(task.createdAt).toLocaleString()}</dd></dl></section>
      <section className="card"><h2>Subtasks</h2><div className="checklist">{task.subtasks.map((s: any) => <label key={s.id}><input type="checkbox" checked={s.completed} onChange={() => toggle(s)} /><span>{s.title}</span></label>)}</div>{(assigned || manager) && <form className="inline-form" onSubmit={addSubtask}><input name="title" required placeholder="Add a checklist item" /><button>Add</button></form>}</section></div>
    <div className="detail-grid"><section className="card"><h2>Comments</h2>{task.comments.map((c: any) => <article className="comment" key={c.id}><span className="table-avatar">{c.author.name[0]}</span><div><b>{c.author.name}</b><small>{new Date(c.createdAt).toLocaleString()}</small><p>{c.content}</p></div></article>)}<form className="inline-form" onSubmit={e => { e.preventDefault(); act("/comments", { content: comment }); }}><input value={comment} onChange={e => setComment(e.target.value)} required placeholder="Add a comment" /><button>Send</button></form></section>
      <section className="card"><h2>Submission history</h2>{task.submissions.map((s: any) => <article className="submission" key={s.id}><b>Submission #{s.submissionNumber}</b><span className={`pill status-${s.status.toLowerCase()}`}>{label(s.status)}</span><p>{s.description}</p><small>{s.submitter.name} · {new Date(s.createdAt).toLocaleString()}</small></article>)}{assigned && ["IN_PROGRESS", "REVISION_REQUIRED"].includes(task.status) && <form onSubmit={e => { e.preventDefault(); act("/submissions", { description: submission }); }}><label>Submit work for review<textarea value={submission} onChange={e => setSubmission(e.target.value)} required /></label><button>Submit for review</button></form>}</section></div>
    <section className="card activity"><h2>Activity</h2><ul>{task.activities.map((a: any) => <li key={a.id}><span className="activity-icon">✦</span><div><b>{label(a.activityType)}</b><p>{a.description} · {a.actor?.name || "System"} · {new Date(a.createdAt).toLocaleString()}</p></div></li>)}</ul></section>
  </Layout>;
}
